package com.mcmoddev.cakeworld.world;

import com.mcmoddev.cakeworld.CakeWorld;

import net.minecraft.world.level.levelgen.feature.Feature;
import net.minecraft.world.level.levelgen.feature.StructureFeature;
import net.minecraftforge.event.RegistryEvent;
import net.minecraftforge.eventbus.api.SubscribeEvent;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.fml.event.lifecycle.FMLCommonSetupEvent;

@Mod.EventBusSubscriber(modid = CakeWorld.MODID, bus = Mod.EventBusSubscriber.Bus.MOD)
public final class CakeWorldFeatureRegistration {
	private CakeWorldFeatureRegistration() {
	}

	@SubscribeEvent
	public static void registerFeatures(RegistryEvent.Register<Feature<?>> event) {
		event.getRegistry().register(StarterPicnicFeature.FEATURE);
		event.getRegistry().register(
				RoadsideCuriosityFeature.FEATURE);
		event.getRegistry().register(
				CookieCrumbGroveFeature.FEATURE);
		event.getRegistry().register(
				PeppermintClearingFeature.FEATURE);
		event.getRegistry().register(
				GummyJungleBounceGroveFeature.FEATURE);
		event.getRegistry().register(
				CaramelBogMangroveFeature.FEATURE);
		event.getRegistry().register(
				SherbetFossilBowlFeature.FEATURE);
		event.getRegistry().register(
				CandyCaneHoodooGardenFeature.FEATURE);
		event.getRegistry().register(
				MarshmallowCloudBridgeFeature.FEATURE);
		event.getRegistry().register(
				IceCreamSundaeRinkFeature.FEATURE);
		event.getRegistry().register(
				WaffleSyrupSkywheelFeature.FEATURE);
		event.getRegistry().register(
				CupcakeBloomCircleFeature.FEATURE);
		event.getRegistry().register(
				LiquoriceRootMazeFeature.FEATURE);
		event.getRegistry().register(
				LollipopTastingGroveFeature.FEATURE);
		event.getRegistry().register(
				PrairiePoppingPatchFeature.FEATURE);
		event.getRegistry().register(
				WaferReefNurseryFeature.FEATURE);
		event.getRegistry().register(
				CustardCoastKitchenFeature.FEATURE);
		event.getRegistry().register(
				JellybeanCompassPicnicFeature.FEATURE);
		event.getRegistry().register(
				RockCandyGeodeBridgeFeature.FEATURE);
		event.getRegistry().register(
				JamLanternWalkFeature.FEATURE);
		event.getRegistry().register(
				AncientNougatKitchenFeature.FEATURE);
		event.getRegistry().register(
				FudgeFondueFountainFeature.FEATURE);
		event.getRegistry().register(
				CinnamonHearthGroveFeature.FEATURE);
		event.getRegistry().register(
				BlackLiquoriceLoopFeature.FEATURE);
		event.getRegistry().register(
				BlackLiquoriceTanglePatchFeature.FEATURE);
		event.getRegistry().register(
				TreacleSoulFlatFeature.FEATURE);
		event.getRegistry().register(
				WispLightCausewayFeature.FEATURE);
		event.getRegistry().register(
				CragfireProspectFeature.FEATURE);
		event.getRegistry().register(
				MallowSteamCalderaFeature.FEATURE);
		event.getRegistry().register(
				MeringueStarLandingFeature.FEATURE);
		event.getRegistry().register(
				CloudstepLookoutFeature.FEATURE);
		event.getRegistry().register(
				CrumbMoonDialFeature.FEATURE);
		event.getRegistry().register(
				SugarStarObservatoryFeature.FEATURE);
		event.getRegistry().register(
				MacaronWayfinderFeature.FEATURE);
		event.getRegistry().register(
				CosmicJellyNurseryFeature.FEATURE);
		event.getRegistry().register(
				BurntToffeeColumnsFeature.FEATURE);
		event.getRegistry().register(GingerbreadVillageFeature.FEATURE);
		event.getRegistry().register(
				BiscuitBanditLookoutFeature.FEATURE);
		event.getRegistry().register(
				WaferMineFeature.FEATURE);
		event.getRegistry().register(
				GrandGingerbreadManorFeature.FEATURE);
		event.getRegistry().register(
				GrandGingerbreadManorRepairFeature.FEATURE);
		event.getRegistry().register(
				GummyShrineFeature.FEATURE);
		event.getRegistry().register(
				GummyShrineRepairFeature.FEATURE);
		event.getRegistry().register(
				SherbetPyramidFeature.FEATURE);
		event.getRegistry().register(
				SherbetPyramidRepairFeature.FEATURE);
		event.getRegistry().register(
				IceCreamParlourFeature.FEATURE);
		event.getRegistry().register(
				IceCreamParlourRepairFeature.FEATURE);
		event.getRegistry().register(
				BurntSugarArchFeature.FEATURE);
		event.getRegistry().register(
				BurntSugarArchRepairFeature.FEATURE);
		event.getRegistry().register(
				WaferWreckFeature.FEATURE);
		event.getRegistry().register(
				WaferWreckRepairFeature.FEATURE);
		event.getRegistry().register(
				CaramelCottageFeature.FEATURE);
		event.getRegistry().register(
				CaramelCottageRepairFeature.FEATURE);
		event.getRegistry().register(
				ConfectionersCottageFeature.FEATURE);
		event.getRegistry().register(
				ConfectionersCottageRepairFeature.FEATURE);
		event.getRegistry().register(
				WaferWindmillFeature.FEATURE);
		event.getRegistry().register(
				WaferWindmillRepairFeature.FEATURE);
		event.getRegistry().register(
				CandyCaneBridgeFeature.FEATURE);
		event.getRegistry().register(
				CandyCaneBridgeRepairFeature.FEATURE);
		event.getRegistry().register(
				CraterKitchenFeature.FEATURE);
		event.getRegistry().register(
				CraterKitchenRepairFeature.FEATURE);
		event.getRegistry().register(
				RockCandyCrystalMineFeature.FEATURE);
		event.getRegistry().register(
				RockCandyCrystalMineRepairFeature.FEATURE);
	}

	@SubscribeEvent
	public static void registerStructureFeatures(
			RegistryEvent.Register<StructureFeature<?>> event) {
		event.getRegistry().register(
				BiscuitBanditLookoutFeature
						.STRUCTURE_FEATURE);
		event.getRegistry().register(
				WaferMineFeature.STRUCTURE_FEATURE);
		event.getRegistry().register(
				GrandGingerbreadManorFeature
						.STRUCTURE_FEATURE);
		event.getRegistry().register(
				GummyShrineFeature.STRUCTURE_FEATURE);
		event.getRegistry().register(
				SherbetPyramidFeature.STRUCTURE_FEATURE);
		event.getRegistry().register(
				IceCreamParlourFeature.STRUCTURE_FEATURE);
		event.getRegistry().register(
				BurntSugarArchFeature.STRUCTURE_FEATURE);
		event.getRegistry().register(
				WaferWreckFeature.STRUCTURE_FEATURE);
		event.getRegistry().register(
				CaramelCottageFeature.STRUCTURE_FEATURE);
		event.getRegistry().register(
				ConfectionersCottageFeature
						.STRUCTURE_FEATURE);
		event.getRegistry().register(
				WaferWindmillFeature.STRUCTURE_FEATURE);
		event.getRegistry().register(
				CandyCaneBridgeFeature
						.STRUCTURE_FEATURE);
		event.getRegistry().register(
				CraterKitchenFeature
						.STRUCTURE_FEATURE);
		event.getRegistry().register(
				RockCandyCrystalMineFeature
						.STRUCTURE_FEATURE);
	}

	@SubscribeEvent
	public static void commonSetup(FMLCommonSetupEvent event) {
		event.enqueueWork(() -> {
			CakeWorldFeaturePoolElement.registerType();
			StarterPicnicFeature.registerConfiguredFeature();
			RoadsideCuriosityFeature
					.registerConfiguredFeature();
			CookieCrumbGroveFeature
					.registerConfiguredFeature();
			PeppermintClearingFeature
					.registerConfiguredFeature();
			GummyJungleBounceGroveFeature
					.registerConfiguredFeature();
			CaramelBogMangroveFeature
					.registerConfiguredFeature();
			SherbetFossilBowlFeature
					.registerConfiguredFeature();
			CandyCaneHoodooGardenFeature
					.registerConfiguredFeature();
			MarshmallowCloudBridgeFeature
					.registerConfiguredFeature();
			IceCreamSundaeRinkFeature
					.registerConfiguredFeature();
			WaffleSyrupSkywheelFeature
					.registerConfiguredFeature();
			CupcakeBloomCircleFeature
					.registerConfiguredFeature();
			LiquoriceRootMazeFeature
					.registerConfiguredFeature();
			LollipopTastingGroveFeature
					.registerConfiguredFeature();
			PrairiePoppingPatchFeature
					.registerConfiguredFeature();
			WaferReefNurseryFeature
					.registerConfiguredFeature();
			CustardCoastKitchenFeature
					.registerConfiguredFeature();
			JellybeanCompassPicnicFeature
					.registerConfiguredFeature();
			RockCandyGeodeBridgeFeature
					.registerConfiguredFeature();
			JamLanternWalkFeature
					.registerConfiguredFeature();
			AncientNougatKitchenFeature
					.registerConfiguredFeature();
			FudgeFondueFountainFeature
					.registerConfiguredFeature();
			CinnamonHearthGroveFeature
					.registerConfiguredFeature();
			BlackLiquoriceLoopFeature
					.registerConfiguredFeature();
			BlackLiquoriceTanglePatchFeature
					.registerConfiguredFeature();
			TreacleSoulFlatFeature
					.registerConfiguredFeature();
			WispLightCausewayFeature
					.registerConfiguredFeature();
			CragfireProspectFeature
					.registerConfiguredFeature();
			MallowSteamCalderaFeature
					.registerConfiguredFeature();
			MeringueStarLandingFeature
					.registerConfiguredFeature();
			CloudstepLookoutFeature
					.registerConfiguredFeature();
			CrumbMoonDialFeature
					.registerConfiguredFeature();
			SugarStarObservatoryFeature
					.registerConfiguredFeature();
			MacaronWayfinderFeature
					.registerConfiguredFeature();
			CosmicJellyNurseryFeature
					.registerConfiguredFeature();
			BurntToffeeColumnsFeature
					.registerConfiguredFeatures();
			GingerbreadVillageFeature.registerWorldgen();
			BiscuitBanditLookoutFeature.registerWorldgen();
			WaferMineFeature.registerWorldgen();
			GrandGingerbreadManorFeature.registerWorldgen();
			GrandGingerbreadManorRepairFeature
					.registerConfiguredFeature();
			GummyShrineFeature.registerWorldgen();
			GummyShrineRepairFeature
					.registerConfiguredFeature();
			SherbetPyramidFeature.registerWorldgen();
			SherbetPyramidRepairFeature
					.registerConfiguredFeature();
			IceCreamParlourFeature.registerWorldgen();
			IceCreamParlourRepairFeature
					.registerConfiguredFeature();
			BurntSugarArchFeature.registerWorldgen();
			BurntSugarArchRepairFeature
					.registerConfiguredFeature();
			WaferWreckFeature.registerWorldgen();
			WaferWreckRepairFeature
					.registerConfiguredFeature();
			CaramelCottageFeature.registerWorldgen();
			CaramelCottageRepairFeature
					.registerConfiguredFeature();
			ConfectionersCottageFeature.registerWorldgen();
			ConfectionersCottageRepairFeature
					.registerConfiguredFeature();
			WaferWindmillFeature.registerWorldgen();
			WaferWindmillRepairFeature
					.registerConfiguredFeature();
			CandyCaneBridgeFeature.registerWorldgen();
			CandyCaneBridgeRepairFeature
					.registerConfiguredFeature();
			CraterKitchenFeature.registerWorldgen();
			CraterKitchenRepairFeature
					.registerConfiguredFeature();
			RockCandyCrystalMineFeature
					.registerWorldgen();
			RockCandyCrystalMineRepairFeature
					.registerConfiguredFeature();
		});
	}
}
